---
- name: Install basic dependencies
  apt: pkg={{item}} force=yes
  sudo: yes
  with_items:
  - build-essential
  - python-pycurl
  - curl
  - htop
  - git
  - make
  - cmake
  - sqlite3
  - libsqlite3-dev
  - autoconf
  - bison
  - libssl-dev
  - libyaml-dev
  - libreadline6
  - libreadline6-dev
  - zlib1g
  - zlib1g-dev
  - vim
