default: &default
  #token: 'd+xBSX+AZ7NQt7mtKQ0o01/JWlEzwaE9EpvXEcTV1kZLx+rUePC+UDnjF+JsHbefKGgRATsyfp/4B6zunTeJ9HNWLqJ1tUDt9l/y5rakH63C3x1sEOusM3GJhVyTB1kxpzYXMZBvx9DLvt/pC1QUkocMrLZxtFZRfl2YZ9bHX48LF0MQVp0iNlbDNmD4U9AdPa2uY+jWf1SLteICTKMWpCg='
  token: 'd651H6K/YQcrzetLIvY6FMQpg01tIAKmIVZakhTtVkONksJIqWG8MRk/1q4tYOp2eABTcpfOHWxH/mBra2sXmCm+MtuqsPI5EDHOQIo5YsZIfGr4kFrk/OEVXa40tKRekoIashBypPdF9AFui6Qve79OMoIlFcqLc55SUORB+9FUFUm7TkQ0mHaClnvRCKHMmTMR0XU2s6aTgjClXTXrYG0='

development:
  <<: *default

production:
  <<: *default
