default: &default
  shipping_country:
    code: "113"
    name: "Korea, Republic of"
    #code: "223"
    #name: "United States"
  categories:
    - cids: "1091,2153,3533,3480"
      auction: "1940100"
      keyword: "3D프린터"
    - cids: "1091,2153,3533,2363"
      auction: "1940100"
      keyword: "3D프린터"
    - cids: "1091,2153,3533,2511"
      auction: "1940100"
      keyword: "3D프린터"

development:
  <<: *default

production:
  <<: *default
