default: &default
  urls:
    - address: "https://www.banggood.com/index.php?com=account&t=dropshipImportDownload&&d_warehouse=CN&d_cid%5B%5D=896&d_cid%5B%5D=1760&d_cid%5B%5D=1894&d_cid%5B%5D=0&sortKey=1&keywords=&add_date_start=&add_date_end=&page=1"
      category: "sport-outdoor/fishing/tools&equipments"

development:
  <<: *default

production:
  <<: *default
