default: &default
  scraper:
    worker_count: 4
    concurrency:
      banggood: 7
      auction: 14
    interval: 6000000

development:
  <<: *default

production:
  <<: *default
  scraper:
    worker_count: 8
