---
- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined
  tags: nginx

- name: Add application directory
  file: dest=/var/www/shopdogg.co.kr state=directory owner=shopdogg group=www-data mode=755
  sudo: yes
  when: env == 'production'
  tags: nginx

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  sudo: yes
  tags: nginx

- name: Ensure nginx is installed.
  apt:
    pkg: nginx
    state: installed
    default_release: "{{ nginx_default_release }}"
  sudo: yes
  tags: nginx

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  sudo: yes
  notify: restart nginx
  tags: 
  - nginx
  - nginx_conf

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
  tags: nginx

- name: Remove default nginx vhost config file (if configured).
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost
  sudo: yes
  notify: restart nginx
  tags:
  - nginx
  - nginx_conf

- name: Add managed vhost config file (if any vhosts are configured).
  template:
    src: vhosts.j2
    dest: "{{ nginx_vhost_path }}/vhosts.conf"
    mode: 0644
  when: nginx_vhosts
  sudo: yes
  notify: restart nginx
  tags:
  - nginx
  - nginx_conf
